const categories = [
  {
    title: "Men's",
    items: [
      {
        label: "Footwear",
        subItems: [
          "Sports Shoes",
          "Casual Shoes",
          "Formal Shoes",
          "Sandals & Floaters",
          "Flip-Flops",
          "Loafers",
          "Boots",
          "Running Shoes",
          "Sneakers",
        ],
      },
      {
        label: "Men's Grooming",
        subItems: [
          "Deodorants",
          "Perfumes",
          "Beard Care & Grooming",
          "Shaving & Aftershave",
          "Sexual Wellness",
        ],
      },
      {
        label: "Clothing",
        subItems: [
          "Top wear",
          "T-Shirts",
          "Formal Shirts",
          "Casual Shirts",
          "Bottom wear",
          "Jeans",
          "Casual Trousers",
          "Formal Trousers",
          "Track pants",
          "Shorts",
          "Cargos",
          "Three Fourths",
          "Suits, Blazers & Waistcoats",
          "Ties, Socks, Caps & More",
          "Fabrics",
          "Winter Wear",
          "Sweatshirts",
          "Jackets",
          "Sweater",
          "Tracksuits",
          "Ethnic wear",
          "Kurta",
          "Ethnic Sets",
          "Sherwanis",
          "Ethnic Pyjama",
          "Dhoti",
          "Lungi",
          "Innerwear & Loungewear",
          "Briefs & Trunks",
          "Vests",
          "Boxers",
          "Pyjamas and Lounge Pants",
          "Thermals",
          "Night Suits",
          "Raincoats & Windcheaters",
        ],
      },
      {
        label: "Watches",
        subItems: ["Fastrack", "Casio", "Titan", "Fossil", "Sonata"],
      },
      {
        label: "Accessories",
        subItems: [
          "Backpacks",
          "Wallets",
          "Belts",
          "Sunglasses",
          "Luggage & Travel",
          "Frames",
          "Jewellery",
        ],
      },
      {
        label: "Sports & Fitness Store",
        subItems: [
          "Smart Watches",
          "Smart Bands",
          "Personal Care Appliances",
          "Trimmers",
          "Shavers",
          "Grooming Kits",
        ],
      },
      {
        label: "Featured",
        subItems: [
          "Watches Store",
          "Footwear Club",
          "Bags & Wallet",
          "T-Shirt Store",
          "Adidas",
          "Beardo",
          "Reebok",
          "Skechers",
          "Nike",
        ],
      },
    ],
  },
  {
    title: "Women's",
    items: [
      {
        label: "Clothing",
        subItems: [
          "Women Western & Maternity Wear",
          "Topwear",
          "Dresses",
          "Jeans",
          "Shorts",
          "Skirts",
          "Jeggings & Tights",
          "Trousers & Capris",
          "Lingerie & Sleepwear",
          "Bras",
          "Panties",
          "Lingerie Sets",
          "Night Dresses & Nighties",
          "Shapewear",
          "Camisoles & Slips",
          "Swim & Beachwear",
          "Party Dresses",
          "Sports Wear",
          "Winter Wear",
          "Ethnic Wear",
          "Sarees",
          "Kurtas & Kurtis",
          "Dress Material",
          "Lehenga Choli",
          "Blouse",
          "Kurta Sets & Salwar Suits",
          "Gowns",
          "Dupattas",
          "Ethnic Bottoms",
          "Leggings & Churidars",
          "Palazzos",
          "Shararas",
          "Salwars & Patiala",
          "Dhoti Pants",
          "Ethnic Trousers",
          "Saree Shapewear & Petticoats",
        ],
      },
      {
        label: "Footwear",
        subItems: [
          "Sandals",
          "Flats",
          "Heels",
          "Wedges",
          "Shoes",
          "Sports Shoes",
          "Casual Shoes",
          "Boots",
          "Ballerinas",
          "Slippers & Flip-Flop's",
        ],
      },
      {
        label: "Watches",
        subItems: ["Smart Watches"],
      },
      {
        label: "Personal Care Appliances",
        subItems: ["Hair Straighteners", "Hair Dryers", "Epilators"],
      },
      {
        label: "Beauty & Grooming",
        subItems: [
          "Make Up",
          "Skin Care",
          "Hair Care",
          "Bath & Spa",
          "Deodorants & Perfumes",
        ],
      },
      {
        label: "Jewellery",
        subItems: [
          "Artificial Jewellery",
          "Silver Jewellery",
          "Precious Jewellery",
          "Coins and Bars",
        ],
      },
      {
        label: "Accessories",
        subItems: [
          "Handbags",
          "Shoulder Bags",
          "Totes",
          "Sling bags",
          "Clutches",
          "Wallets & Belts",
          "Luggage & Travel",
          "Sunglasses",
          "Frames",
        ],
      },
      {
        label: "Featured",
        subItems: [
          "Forever 21",
          "Accessorize",
          "W",
          "Pantaloons",
          "Chemistry",
          "Lakme",
          "Nivea",
          "Catwalk",
          "Titan-Raga",
          "Fastrack",
          "Divastri",
          "Rare Roots",
          "Anmi",
          "Coins & Bars",
          "Crocs",
        ],
      },
      {
        label: "Trending today!",
        subItems: [
          "Ruffles & Frills",
          "Pastel Kurtas & Kurtis",
          "Designer Net Sarees",
        ],
      },
    ],
  },
];

export default categories;
